server:
  port: 7000

spring:
  application:
    name: reactive-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: app-product-mall
          uri: lb://app-product-mall
          predicates:
            - Path=/mall/**
          filters:
            - RewritePath=/mall/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
